apiVersion: v1
kind: Service
metadata:
  name: redis 
  namespace: xmc2
spec:
 # type: ClusterIP
  ports:
  - port: 6379  #服务暴露的端口
    protocol: TCP
    targetPort: 6379  #容器暴露的端口
  selector: #关联的Pod的标签
    app: redis
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: redis
  namespace: xmc2
spec:
   replicas: 1
   template:
     metadata:
       labels:
         app: redis
     spec:
       containers:
       - name: redis
         image: redis
         ports:
         - containerPort: 6379
         env:
         - name: TZ
           value: Asia/Shanghai
